#include "Interpreter.h"
#include "InterpreterTable.h"
#include "isa-sm83.h"

// SM83 Instructions
static void NOP(struct Interpreter* interpreter);

static void LD_B_BUS(struct Interpreter* interpreter);
static void LD_C_BUS(struct Interpreter* interpreter);
static void LD_D_BUS(struct Interpreter* interpreter);
static void LD_E_BUS(struct Interpreter* interpreter);
static void LD_H_BUS(struct Interpreter* interpreter);
static void LD_L_BUS(struct Interpreter* interpreter);
static void LD_A_BUS(struct Interpreter* interpreter);
static void LD_HL_BUS(struct Interpreter* interpreter);

// nop
DEFINE_INSTRUCTION(NOP, );

// 8-bit load/store instruction
// ld r,r
DEFINE_LD_B_INSTRUCTION(B, cpuState.b);
DEFINE_LD_B_INSTRUCTION(C, cpuState.c);
DEFINE_LD_B_INSTRUCTION(D, cpuState.d);
DEFINE_LD_B_INSTRUCTION(E, cpuState.e);
DEFINE_LD_B_INSTRUCTION(H, cpuState.h);
DEFINE_LD_B_INSTRUCTION(L, cpuState.l);
DEFINE_LD_B_INSTRUCTION(A, cpuState.a);
DEFINE_LD_C_INSTRUCTION(B, cpuState.b);
DEFINE_LD_C_INSTRUCTION(C, cpuState.c);
DEFINE_LD_C_INSTRUCTION(D, cpuState.d);
DEFINE_LD_C_INSTRUCTION(E, cpuState.e);
DEFINE_LD_C_INSTRUCTION(H, cpuState.h);
DEFINE_LD_C_INSTRUCTION(L, cpuState.l);
DEFINE_LD_C_INSTRUCTION(A, cpuState.a);
DEFINE_LD_D_INSTRUCTION(B, cpuState.b);
DEFINE_LD_D_INSTRUCTION(C, cpuState.c);
DEFINE_LD_D_INSTRUCTION(D, cpuState.d);
DEFINE_LD_D_INSTRUCTION(E, cpuState.e);
DEFINE_LD_D_INSTRUCTION(H, cpuState.h);
DEFINE_LD_D_INSTRUCTION(L, cpuState.l);
DEFINE_LD_D_INSTRUCTION(A, cpuState.a);
DEFINE_LD_E_INSTRUCTION(B, cpuState.b);
DEFINE_LD_E_INSTRUCTION(C, cpuState.c);
DEFINE_LD_E_INSTRUCTION(D, cpuState.d);
DEFINE_LD_E_INSTRUCTION(E, cpuState.e);
DEFINE_LD_E_INSTRUCTION(H, cpuState.h);
DEFINE_LD_E_INSTRUCTION(L, cpuState.l);
DEFINE_LD_E_INSTRUCTION(A, cpuState.a);
DEFINE_LD_H_INSTRUCTION(B, cpuState.b);
DEFINE_LD_H_INSTRUCTION(C, cpuState.c);
DEFINE_LD_H_INSTRUCTION(D, cpuState.d);
DEFINE_LD_H_INSTRUCTION(E, cpuState.e);
DEFINE_LD_H_INSTRUCTION(H, cpuState.h);
DEFINE_LD_H_INSTRUCTION(L, cpuState.l);
DEFINE_LD_H_INSTRUCTION(A, cpuState.a);
DEFINE_LD_L_INSTRUCTION(B, cpuState.b);
DEFINE_LD_L_INSTRUCTION(C, cpuState.c);
DEFINE_LD_L_INSTRUCTION(D, cpuState.d);
DEFINE_LD_L_INSTRUCTION(E, cpuState.e);
DEFINE_LD_L_INSTRUCTION(H, cpuState.h);
DEFINE_LD_L_INSTRUCTION(L, cpuState.l);
DEFINE_LD_L_INSTRUCTION(A, cpuState.a);

DEFINE_LD_B_INSTRUCTION(BUS, bus);
DEFINE_LD_C_INSTRUCTION(BUS, bus);
DEFINE_LD_D_INSTRUCTION(BUS, bus);
DEFINE_LD_E_INSTRUCTION(BUS, bus);
DEFINE_LD_H_INSTRUCTION(BUS, bus);
DEFINE_LD_L_INSTRUCTION(BUS, bus);
DEFINE_LD_A_INSTRUCTION(BUS, bus);

// ld r,n
DEFINE_LD_R_N_INSTRUCTION(B);
DEFINE_LD_R_N_INSTRUCTION(C);
DEFINE_LD_R_N_INSTRUCTION(D);
DEFINE_LD_R_N_INSTRUCTION(E);
DEFINE_LD_R_N_INSTRUCTION(H);
DEFINE_LD_R_N_INSTRUCTION(L);
DEFINE_LD_R_N_INSTRUCTION(A);

// ld r,(HL)
DEFINE_LD_R_HL_INSTRUCTION(B);
DEFINE_LD_R_HL_INSTRUCTION(C);
DEFINE_LD_R_HL_INSTRUCTION(D);
DEFINE_LD_R_HL_INSTRUCTION(E);
DEFINE_LD_R_HL_INSTRUCTION(H);
DEFINE_LD_R_HL_INSTRUCTION(L);
DEFINE_LD_R_HL_INSTRUCTION(A);

// ld (HL),r
DEFINE_LD_HL_INSTRUCTION(B, cpuState.b);
DEFINE_LD_HL_INSTRUCTION(C, cpuState.c);
DEFINE_LD_HL_INSTRUCTION(D, cpuState.d);
DEFINE_LD_HL_INSTRUCTION(E, cpuState.e);
DEFINE_LD_HL_INSTRUCTION(H, cpuState.h);
DEFINE_LD_HL_INSTRUCTION(L, cpuState.l);
DEFINE_LD_HL_INSTRUCTION(A, cpuState.a);

DEFINE_LD_HL_INSTRUCTION(BUS, bus);

// ld (HL),n
DEFINE_LD_HL_N_INSTRUCTION;

// ld A,(BC)
DEFINE_LD_A_BC_INSTRUCTION;

// ld A,(nn)
DEFINE_LD_A_NN_INSTRUCTION;

// ld (BC),A
DEFINE_LD_BC_A_INSTRUCTION;

// ld (DE),A
DEFINE_LD_DE_A_INSTRUCTION;

// ld (nn),A
DEFINE_LD_NN_A_INSTRUCTION;

// ld A,(FF00+n)
DEFINE_LDH_A_N_INSTRUCTION;

// ld A,(FF00+C)
DEFINE_LDH_A_C_INSTRUCTION;

// ld (FF00+C),A
DEFINE_LDH_C_A_INSTRUCTION;

// ldi A
DEFINE_LDI_A_HL_INSTRUCTION;

DEFINE_LDD_A_HL_INSTRUCTION;

DEFINE_LDI_HL_A_INSTRUCTION;

DEFINE_LDD_HL_A_INSTRUCTION;

//16-bit load/store instruction
// ld rr,nn
DEFINE_LD_RR_NN_INSTRUCTION(BC, cpuState.b, cpuState.c);
DEFINE_LD_RR_NN_INSTRUCTION(DE, cpuState.d, cpuState.e);
DEFINE_LD_RR_NN_INSTRUCTION(HL, cpuState.h, cpuState.l);
DEFINE_LD_SP_NN_INSTRUCTION;

// ld SP,HL
DEFINE_LD_SP_HL;

// ld (nn),SP
DEFINE_LD_NN_SP_INSTRUCTION;

// push rr
DEFINE_PUSH_RR_INSTRUCTION(BC, cpuState.b, cpuState.c);
DEFINE_PUSH_RR_INSTRUCTION(DE, cpuState.d, cpuState.e);
DEFINE_PUSH_RR_INSTRUCTION(HL, cpuState.h, cpuState.l);
DEFINE_PUSH_RR_INSTRUCTION(AF, cpuState.a, cpuState.f.packed);

// pop rr
DEFINE_POP_RR_INSTRUCTION(B, C, cpuState.b, cpuState.c);
DEFINE_POP_RR_INSTRUCTION(D, E, cpuState.d, cpuState.e);
DEFINE_POP_RR_INSTRUCTION(H, L, cpuState.h, cpuState.l);
DEFINE_POP_RR_INSTRUCTION(A, F, cpuState.a, cpuState.f.packed);

// 8-bit ALU ops
DEFINE_ADD_A_R_INSTRUCTION(B, cpuState.b);
DEFINE_ADD_A_R_INSTRUCTION(C, cpuState.c);
DEFINE_ADD_A_R_INSTRUCTION(D, cpuState.d);
DEFINE_ADD_A_R_INSTRUCTION(E, cpuState.e);
DEFINE_ADD_A_R_INSTRUCTION(H, cpuState.h);
DEFINE_ADD_A_R_INSTRUCTION(L, cpuState.l);
DEFINE_ADD_A_R_INSTRUCTION(A, cpuState.a);

DEFINE_ADD_A_N_INSTRUCTION;
DEFINE_ADD_A_HL_INSTRUCTION;

DEFINE_ADC_A_R_INSTRUCTION(B, cpuState.b);
DEFINE_ADC_A_R_INSTRUCTION(C, cpuState.c);
DEFINE_ADC_A_R_INSTRUCTION(D, cpuState.d);
DEFINE_ADC_A_R_INSTRUCTION(E, cpuState.e);
DEFINE_ADC_A_R_INSTRUCTION(H, cpuState.h);
DEFINE_ADC_A_R_INSTRUCTION(L, cpuState.l);
DEFINE_ADC_A_R_INSTRUCTION(A, cpuState.a);

DEFINE_ADC_A_N_INSTRUCTION;
DEFINE_ADC_A_HL_INSTRUCTION;

DEFINE_SUB_A_R_INSTRUCTION(B, cpuState.b);
DEFINE_SUB_A_R_INSTRUCTION(C, cpuState.c);
DEFINE_SUB_A_R_INSTRUCTION(D, cpuState.d);
DEFINE_SUB_A_R_INSTRUCTION(E, cpuState.e);
DEFINE_SUB_A_R_INSTRUCTION(H, cpuState.h);
DEFINE_SUB_A_R_INSTRUCTION(L, cpuState.l);
DEFINE_SUB_A_R_INSTRUCTION(A, cpuState.a);

DEFINE_SUB_A_N_INSTRUCTION;
DEFINE_SUB_A_HL_INSTRUCTION;

DEFINE_SBC_A_R_INSTRUCTION(B, cpuState.b);
DEFINE_SBC_A_R_INSTRUCTION(C, cpuState.c);
DEFINE_SBC_A_R_INSTRUCTION(D, cpuState.d);
DEFINE_SBC_A_R_INSTRUCTION(E, cpuState.e);
DEFINE_SBC_A_R_INSTRUCTION(H, cpuState.h);
DEFINE_SBC_A_R_INSTRUCTION(L, cpuState.l);
DEFINE_SBC_A_R_INSTRUCTION(A, cpuState.a);

DEFINE_SBC_A_N_INSTRUCTION;
DEFINE_SBC_A_HL_INSTRUCTION;

// jmp instructions
DEFINE_JP_NN_INSTRUCTION;
DEFINE_JP_HL_INSTRUCTION;

DEFINE_JP_NN_CONDITIONAL_INSTRUCTION;

DEFINE_JR_NN_INSTRUCTION;

DEFINE_JR_CONDITIONAL_NN_INSTRUCTION;

DEFINE_CALL_NN_INSTRUCTION;

DEFINE_CALL_CONDITIONAL_NN_INSTRUCTION;

#define DECLARE_INTERPRETER_TABLE \
    NOP, \

const SM83Instruction sm83InterpreterTable[0x100] = {
    DECLARE_INTERPRETER_TABLE
};



















